### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by mxnmnm** [ITsMrToad/PalladiumMod#12] opened 2024-08-28 16:31 UTC
There is some weird conflict going on. I will narrow down the mods but I figured I'd just make the report rn. I will update you on what I find

https://gist.github.com/mxnmnm/613bed835e8212f0959aa517fd203453

**Comment by mxnmnm** [comment] 2024-08-29 02:16
Ok I think the issue was caused by dynamic resources from modern fix. I would really like for this to be compatible with that because without it loading times are horrific

**Comment by ITsMrToad** [comment] 2024-08-29 02:17
The conflict is caused by one of these mods: ```brute_force_rendering_culling```, ```littletiles```, ```nvidium```, ```fabric_model_loading_api_v1```.

**Comment by ITsMrToad** [comment] 2024-08-29 02:18
> Ok I think the issue was caused by dynamic resources from modern fix. I would really like for this to be compatible with that because without it loading times are horrific

What makes you think that?

**Comment by mxnmnm** [comment] 2024-08-29 02:19
I narrowed it down. The mods you listed are not the cause, those are always mentioned as being problematic but have never actually been the issue from what I've seen. I've had them mentioned in completely different reports that were unrelated.

**Comment by mxnmnm** [comment] 2024-08-29 02:20
https://gist.github.com/mxnmnm/d57600edcc8438cbe2270d67e919a23c here is a fresh report

**Comment by ITsMrToad** [comment] 2024-08-29 02:24
Palladium compatible with modern fix(I tested them in a large modpack on 1.20.1)

**Comment by mxnmnm** [comment] 2024-08-29 02:24
Yes, but I'm talking about modern fix with the dynamic resources mixin enabled which has a HUGE performance boost.

**Comment by mxnmnm** [comment] 2024-08-29 02:24
Loading times go from 1min to 5mins without it enabled

**Comment by ITsMrToad** [comment] 2024-08-29 04:01
Fixed in 1.0.1

**Closed as completed** 2024-08-29 14:05 UTC
Labels: compat
